spring:
  application:
    name: demoCiCd

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true
    username: postgres.faumaujitazuxhohbtnm
    password: AnmolMehla@6228
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080
# spring:
#   application:
#     name: demoCiCd

#   datasource:
#     url: jdbc:mysql://localhost:3306/pay
#     username: root
#     password: Mehla@6228
#     driver-class-name: com.mysql.cj.jdbc.Driver

#     hikari:
#       minimum-idle: 2
#       maximum-pool-size: 5
#       idle-timeout: 30000
#       connection-timeout: 20000
#       max-lifetime: 1800000

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect