spring:
  application:
    name: demoCiCd

  datasource:
    url: ${DB_URL:jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${DB_USERNAME:postgres.faumaujitazuxhohbtnm}
    password: ${DB_PASSWORD:AnmolMehla@6228}
    driver-class-name: org.postgresql.Driver

    hikari:
      minimum-idle: 1
      maximum-pool-size: 3      # reduce to avoid max clients error
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
